<?php
/**
 * @file
 * Provide custom IPGroup vacancy feedback page and hooks implementations.
 */

/**
 * Implements hook_menu().
 */
function ipg_vacancy_menu() {
  $items['vacancies/feedback'] = array(
    'page callback' => 'ipg_vacancy_feedback_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function ipg_vacancy_feedback_page() {
  $nid = arg(2);
  return drupal_get_form('ipg_vacancy_feedback_form', $nid);
}

function ipg_vacancy_feedback_form($form, &$form_state, $nid) {

  $view = views_get_view('article');
  $view->set_display('vacancies_list_pane');
  $view->pre_execute();
  $view->execute();

  $vacancies = array();
  foreach ($view->result as $result) {
    $vacancies[$result->nid] = $result->node_title;
  }

  $form['vacancy'] = array(
    '#type' => 'select',
    '#title' => t('Vacancy'),
    '#options' => $vacancies,
    '#description' => t('Select the vacancy you want to apply to.'),
    '#required' => TRUE,
    '#default_value' => $nid,
  );
  $form['first_name'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#required' => TRUE,
    '#default_value' => NULL,
  );
  $form['last_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#required' => TRUE,
    '#default_value' => NULL,
  );
  $form['mail'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#description' => t('Insert your e-mail address.'),
    '#required' => TRUE,
    '#default_value' => NULL,
  );
  $form['text'] = array(
    '#type' => 'textarea',
    '#title' => t('Some comments'),
    '#default_value' => NULL,
  );
  $form['file'] = array(
    '#type' => 'file',
    '#title' => t('CV file'),
    '#default_value' => NULL,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );

  return $form;
}

function ipg_vacancy_feedback_form_validate(&$form, &$form_state) {
  $values = $form_state['values'];

  if (!valid_email_address($values['mail'])){
    form_set_error('mail', t('The mail is invalid.'));
  }



  $file = file_save_upload('file', array());
  if ($file) {
    $form_state['storage']['file'] = $file;
  } else {
    form_set_error('file', t('No file was uploaded.'));
  }
}

function ipg_vacancy_feedback_form_submit(&$form, &$form_state) {
  global $language;
  $values = $form_state['values'];

  $params = $values;
  $params['vacancy'] = $form['vacancy']['#options'][$values['vacancy']];
  $params['file'] = $form_state['storage']['file'];

  drupal_mail('ipg_vacancy', 'ipg_vacancy_feedback', 'job@ipgroup.md', $language, $params, $from = NULL, $send = TRUE);
  drupal_set_message(t('Your application has been sent. We will contact you soon.'));
}

/**
 * Implements hook_mail().
 */
function ipg_vacancy_mail($key, &$message, $params) {
  if ($key == 'ipg_vacancy_feedback') {
    $variables = array(
      '%first_name' => $params['first_name'],
      '%last_name' => $params['last_name'],
      '%mail' => $params['mail'],
      '%text' => $params['text'],
      '%vacancy' => $params['vacancy'],
    );
    $attachment = array(
      'filecontent' => file_get_contents($params['file']->uri),
      'filename' => $params['file']->filename,
      'filemime' => $params['file']->filemime,
    );

    $subject = t('New request for %vacancy vacancy');
    $body = t('%first_name %last_name sent request for %vacancy vacancy.');
    $body .= "\n" . t('Contact email: %mail');
    if (!empty($params['text'])) {
      $body .= "\n" . t('Comment: %text');
    }

    $message['subject'] = strtr($subject, $variables);
    $message['body'][] = strtr($body, $variables);
    $message['params']['attachments'][] = $attachment;
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function ipg_vacancy_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}
